services:
  api:
    image: ghcr.io/iluhaprogrammer/fastapi-api:latest
    restart: always
    networks:
      - backend
  
  nginx:
    image: ghcr.io/iluhaprogrammer/fastapi-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always
    volumes:
      - nginx_data:/var/log/nginx:w
    networks:
      - backend
      - frontend

volumes:
  nginx_data:

networks:
  frontend:
  backend: