services:
  project-api:
    image: ghcr.io/iluhaprogrammer/fastapi-api:latest
    restart: always
    networks:
      - project_backend
  
  project-nginx:
    image: ghcr.io/iluhaprogrammer/fastapi-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - project-api
    restart: always
    volumes:
      - project_nginx_data:/var/log/nginx:w
    networks:
      - project_backend
      - project_frontend

volumes:
  project_nginx_data:

networks:
  project_frontend:
  project_backend: