name: FastAPI CI/CD

on:
  push:
    branches: ["dev, main"]

permissions:
  contents: read
  packages: write

env: 
  REGISTRY: ghcr.io
  IMAGE_API: fastapi-api
  IMAGE_NGINX: fastapi-nginx

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositories
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
        
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      
      - name: Install dependencies
        run: pip install flake8 pytest fastapi uvicorn 
      
      - name: Run flake8
        run: flake8 app
      
      - name: Run tests
        run: pytest

  build-push:
    needs: lint-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login docker registry 
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push image API 
        uses: docker/build-push-action@v5
        with: 
          content: /app
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/iluhaprogrammer/${{ env.IMAGE_API }}:latest
          cache-from: type=registry,ref=ghcr.io/iluhaprogrammer/${{ env.IMAGE_API }}:buildcache
          cache-to: type=registry,mode=max,ref=ghcr.io/iluhaprogrammer/${{ env.IMAGE_API }}:buildcache
        
      - name: Build and push image NGINX 
        uses: docker/build-push-action@v5
        with: 
          content: /nginx
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/iluhaprogrammer/${{ env.IMAGE_NGINX }}:latest
          cache-from: type=registry,ref=ghcr.io/iluhaprogrammer/${{ env.IMAGE_NGINX }}:buildcache
          cache-to: type=registry,mode=max,ref=ghcr.io/iluhaprogrammer/${{ env.IMAGE_NGINX }}:buildcache
  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST}}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script:
            cd /home/hasler4444/project
            docker compose pull 
            docker compose up -d 
        